### ISSUE TITLE
Integration with run.dlang.io

### ISSUE THREAD

**Issue by wilzbach** [marler8997/har#3]
I try to keep myself short. The interesting bit is here: 

https://github.com/dlang-tour/core-exec/blob/master/entrypoint.sh (I know that this file is ugly).

Anyhow, there are only two things that would need to be done:

1) Compile `har` into the Docker image (easy)
2) Call `har` after this line:

```
echo "$1" | base64 -d > onlineapp.d
```

What I was wondering about is whether har could have a machine-readable output for run.dlang.io

```bash
echo "$1" | base64 -d > onlineapp.d
harResult=$(har onlineapp.d)
if [ $? -eq 0 ] ; then
    mainApp="$harResult" // <- the logic below needs to know what the main module is
fi
```

So I'm thinking about e.g. verbose flag that prints the extracted files, s.t. I can do sth. along these lines:

```d
har -v onlineapp.d | grep "*.d" | head -n1
```

I know that har is rather simple and at the moment `grep "--- *.d"` would work too, but I would prefer to avoid that.

Also note that once run.dlang.io supports har, it would auto-magically work for forum.dlang.org too (well at least once I finally get around hacking a Markdown transformation into DFeed).

**Comment by marler8997** [comment]
I was already planning on adding a machine parseable output to HAR. I'll implement it tonight/tomorrow.

**Comment by wilzbach** [comment]
Thanks. No pressure!

**Comment by marler8997** [comment]
Ok...I've flushed out the standard and implementation alot more.

Now if you run `har myfile.har` the extracted files will be printed to stdout and nothing else.  Errors will go to `stderr` and the exit code should work as expected.  If you need to distinguish filenames with directories, directories will always be followed with a trailing slash `/`.  i.e.
```
> har foo/myfile.har
foo/myfile/main.d
foo/myfile/foo.d
foo/myfile/emptydir/
```

Use `--dir=` to override the default output directory
```
har --dir=outputdir foo/myfile.har
outputdir/main.d
outputdir/foo.d
outputdir/emptydir/
```

Note, you don't have to create the output directory before extracting to it.

I also made sure that `..` directories could not be used to extract files outside the output directory.

**Comment by marler8997** [comment]
I was thinking how you were going to tell if the user means to input HAR or just D.  You could check the first line to see if it starts with 3 dashes and a space (or just a bunch of dashes and a space if we want to be more lenient with delimiters).

What I would want to prevent is assuming the user meant to input D if they have an error in their HAR input.  This would cause the HAR extract to fail but if we assume it was meant to be D then we won't know to give the HAR error message to the user.

I'm no BASH guru so this is mostly pseudo-code:
```BASH
if [ startsWith("$1", "--- ") ]; then
    # assume HAR format
    harResult=$(har onlineapp.d)
    if [ $? -ne 0 ] ; then
        # copy stderr messages to user
    fi
    mainApp="$harResult" // <- the logic below needs to know what the main module is
fi
```

**Comment by wilzbach** [comment]
An initial test to see how easy it is to integrate har and it's really straight-forward :)

https://github.com/dlang-tour/core-exec/pull/34

It's already live: https://run.dlang.io/is/7MczEl

It still has a few problems, e.g.
- the output file return logic hasn't been adapted (so the JSON/AST/ASM button won't work for now)
- it puts everything into the `onlineapp` folder (will fix that soon)
- it just uses `dmd a b c` for now (will fix that to use `rdmd` for the time being)

**Comment by marler8997** [comment]
Didn't seem to work with multiple files:

https://run.dlang.io/?compiler=dmd&source=---%20test.d%0Aimport%20std.stdio;%0Avoid%20main()%0A%7B%0A%20%20%20%20%20__FILE__.writeln;%0A%7D

Looks like we might need to add an import path?

**Comment by wilzbach** [comment]
> Didn't seem to work with multiple files:

Oh I thought I mentioned that it needs to be extracted to `$PWD` and also use `rdmd` for now as DMD's builtin `-run` doesn't work well with multiple files :/

Anyhow update is on the merge and deploy queue: https://github.com/dlang-tour/core-exec/pull/35
